/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  BlocklistAdminRole,
  BlocklistAdminRoleInterface,
} from "../BlocklistAdminRole";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "account",
        type: "address",
      },
    ],
    name: "isBlocklistAdmin",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "account",
        type: "address",
      },
    ],
    name: "addBlocklistAdmin",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "token",
        type: "address",
      },
    ],
    name: "renounceBlocklistAdmin",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "account",
        type: "address",
      },
    ],
    name: "removeBlocklistAdmin",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        name: "account",
        type: "address",
      },
    ],
    name: "BlocklistAdminAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        name: "account",
        type: "address",
      },
    ],
    name: "BlocklistAdminRemoved",
    type: "event",
  },
];

export class BlocklistAdminRole__factory {
  static readonly abi = _abi;
  static createInterface(): BlocklistAdminRoleInterface {
    return new utils.Interface(_abi) as BlocklistAdminRoleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BlocklistAdminRole {
    return new Contract(address, _abi, signerOrProvider) as BlocklistAdminRole;
  }
}
