/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ClockMock, ClockMockInterface } from "../ClockMock";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getTime",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060788061001e6000396000f3fe6080604052348015600f57600080fd5b5060043610602b5760e060020a6000350463557ed1ba81146030575b600080fd5b60366048565b60408051918252519081900360200190f35b429056fea165627a7a723058205cfc9b87e0c1c4137bc26b3d6c61cab3704b4b8b1ad80d6b9006158a1fbc05530029";

export class ClockMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ClockMock> {
    return super.deploy(overrides || {}) as Promise<ClockMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ClockMock {
    return super.attach(address) as ClockMock;
  }
  connect(signer: Signer): ClockMock__factory {
    return super.connect(signer) as ClockMock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClockMockInterface {
    return new utils.Interface(_abi) as ClockMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ClockMock {
    return new Contract(address, _abi, signerOrProvider) as ClockMock;
  }
}
