/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ERC165MappingImplementation,
  ERC165MappingImplementationInterface,
} from "../ERC165MappingImplementation";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

export class ERC165MappingImplementation__factory {
  static readonly abi = _abi;
  static createInterface(): ERC165MappingImplementationInterface {
    return new utils.Interface(_abi) as ERC165MappingImplementationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC165MappingImplementation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC165MappingImplementation;
  }
}
