/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Extension, ExtensionInterface } from "../Extension";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "certificateActivated",
        type: "uint8",
      },
      {
        name: "allowlistActivated",
        type: "bool",
      },
      {
        name: "blocklistActivated",
        type: "bool",
      },
      {
        name: "granularityByPartitionActivated",
        type: "bool",
      },
      {
        name: "holdsActivated",
        type: "bool",
      },
      {
        name: "operators",
        type: "address[]",
      },
    ],
    name: "registerTokenSetup",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "account",
        type: "address",
      },
    ],
    name: "addCertificateSigner",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Extension__factory {
  static readonly abi = _abi;
  static createInterface(): ExtensionInterface {
    return new utils.Interface(_abi) as ExtensionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Extension {
    return new Contract(address, _abi, signerOrProvider) as Extension;
  }
}
