/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAuthProvider, IAuthProviderInterface } from "../IAuthProvider";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "addr",
        type: "address",
      },
      {
        name: "latestAcceptedTimestamp",
        type: "uint256",
      },
    ],
    name: "hasAuthenticated",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IAuthProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthProviderInterface {
    return new utils.Interface(_abi) as IAuthProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAuthProvider {
    return new Contract(address, _abi, signerOrProvider) as IAuthProvider;
  }
}
