/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LegacyCBReturnFalse,
  LegacyCBReturnFalseInterface,
} from "../LegacyCBReturnFalse";

const _abi = [
  {
    payable: false,
    stateMutability: "nonpayable",
    type: "fallback",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50604780601d6000396000f3fe6080604052348015600f57600080fd5b50600160005260206000f3fea165627a7a723058200b206143476baacd5192a7eb3aee33619bbb06c8b606d380f55e8205788d4c8d0029";

export class LegacyCBReturnFalse__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LegacyCBReturnFalse> {
    return super.deploy(overrides || {}) as Promise<LegacyCBReturnFalse>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LegacyCBReturnFalse {
    return super.attach(address) as LegacyCBReturnFalse;
  }
  connect(signer: Signer): LegacyCBReturnFalse__factory {
    return super.connect(signer) as LegacyCBReturnFalse__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LegacyCBReturnFalseInterface {
    return new utils.Interface(_abi) as LegacyCBReturnFalseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LegacyCBReturnFalse {
    return new Contract(address, _abi, signerOrProvider) as LegacyCBReturnFalse;
  }
}
