/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LegacyCBReturnTrue,
  LegacyCBReturnTrueInterface,
} from "../LegacyCBReturnTrue";

const _abi = [
  {
    payable: false,
    stateMutability: "nonpayable",
    type: "fallback",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50604780601d6000396000f3fe6080604052348015600f57600080fd5b50600160005260206000f3fea165627a7a723058205bd35307a8dfca5d3d0c499a99306e90855e160ba0cfb9cc8a39a5d38200284a0029";

export class LegacyCBReturnTrue__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LegacyCBReturnTrue> {
    return super.deploy(overrides || {}) as Promise<LegacyCBReturnTrue>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LegacyCBReturnTrue {
    return super.attach(address) as LegacyCBReturnTrue;
  }
  connect(signer: Signer): LegacyCBReturnTrue__factory {
    return super.connect(signer) as LegacyCBReturnTrue__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LegacyCBReturnTrueInterface {
    return new utils.Interface(_abi) as LegacyCBReturnTrueInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LegacyCBReturnTrue {
    return new Contract(address, _abi, signerOrProvider) as LegacyCBReturnTrue;
  }
}
