/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LegacyCBNoReturn,
  LegacyCBNoReturnInterface,
} from "../LegacyCBNoReturn";

const _abi = [
  {
    payable: false,
    stateMutability: "nonpayable",
    type: "fallback",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052348015600f57600080fd5b5000fea165627a7a72305820ad5baa8b5582c645d9de23b046740986dc2963c53691a7861ccd0522e0c044fc0029";

export class LegacyCBNoReturn__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LegacyCBNoReturn> {
    return super.deploy(overrides || {}) as Promise<LegacyCBNoReturn>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LegacyCBNoReturn {
    return super.attach(address) as LegacyCBNoReturn;
  }
  connect(signer: Signer): LegacyCBNoReturn__factory {
    return super.connect(signer) as LegacyCBNoReturn__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LegacyCBNoReturnInterface {
    return new utils.Interface(_abi) as LegacyCBNoReturnInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LegacyCBNoReturn {
    return new Contract(address, _abi, signerOrProvider) as LegacyCBNoReturn;
  }
}
