/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AuthProviderInterface extends ethers.utils.Interface {
  functions: {
    "authenticate(address)": FunctionFragment;
    "controllers()": FunctionFragment;
    "hasAuthenticated(address,uint256)": FunctionFragment;
    "isAuthenticated(address)": FunctionFragment;
    "lastAuth(address)": FunctionFragment;
    "setControllers(address[])": FunctionFragment;
    "setTTL(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "authenticate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "controllers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAuthenticated",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthenticated",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "lastAuth", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setControllers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTTL",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authenticate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAuthenticated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthenticated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastAuth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTTL", data: BytesLike): Result;

  events: {};
}

export class AuthProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AuthProviderInterface;

  functions: {
    authenticate(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controllers(overrides?: CallOverrides): Promise<[string[]]>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isAuthenticated(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lastAuth(addr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTTL(
      time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  authenticate(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controllers(overrides?: CallOverrides): Promise<string[]>;

  hasAuthenticated(
    addr: string,
    latestAcceptedTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isAuthenticated(addr: string, overrides?: CallOverrides): Promise<boolean>;

  lastAuth(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  setControllers(
    operators: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTTL(
    time: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    authenticate(addr: string, overrides?: CallOverrides): Promise<void>;

    controllers(overrides?: CallOverrides): Promise<string[]>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAuthenticated(addr: string, overrides?: CallOverrides): Promise<boolean>;

    lastAuth(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTTL(time: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    authenticate(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controllers(overrides?: CallOverrides): Promise<BigNumber>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAuthenticated(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastAuth(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTTL(
      time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authenticate(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controllers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAuthenticated(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastAuth(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTTL(
      time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
