/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CapTableQueInterface extends ethers.utils.Interface {
  functions: {
    "add(address,bytes32)": FunctionFragment;
    "controllers()": FunctionFragment;
    "getRegistry()": FunctionFragment;
    "getStatus(address)": FunctionFragment;
    "info(address)": FunctionFragment;
    "isController(address)": FunctionFragment;
    "list()": FunctionFragment;
    "listApproved()": FunctionFragment;
    "listDeclined()": FunctionFragment;
    "listQued()": FunctionFragment;
    "process(address,bool,bytes32)": FunctionFragment;
    "setControllers(address[])": FunctionFragment;
    "setRegistry(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "add",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controllers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values: [string]): string;
  encodeFunctionData(functionFragment: "info", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isController",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "list", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "listApproved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listDeclined",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "listQued", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "process",
    values: [string, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setControllers",
    values: [string[]]
  ): string;
  encodeFunctionData(functionFragment: "setRegistry", values: [string]): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "controllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "list", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listDeclined",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listQued", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "process", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;

  events: {
    "qued(address)": EventFragment;
    "statusUpdate(address,uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "qued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "statusUpdate"): EventFragment;
}

export class CapTableQue extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CapTableQueInterface;

  functions: {
    add(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controllers(overrides?: CallOverrides): Promise<[string[]]>;

    getRegistry(
      overrides?: CallOverrides
    ): Promise<[string] & { capTableRegistry: string }>;

    getStatus(adr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    info(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { status: BigNumber; uuid: string }>;

    isController(adr: string, overrides?: CallOverrides): Promise<[boolean]>;

    list(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    listApproved(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    listDeclined(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    listQued(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    process(
      adr: string,
      approved: boolean,
      reason: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRegistry(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  add(
    adr: string,
    uuid: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controllers(overrides?: CallOverrides): Promise<string[]>;

  getRegistry(overrides?: CallOverrides): Promise<string>;

  getStatus(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

  info(
    adr: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { status: BigNumber; uuid: string }>;

  isController(adr: string, overrides?: CallOverrides): Promise<boolean>;

  list(overrides?: CallOverrides): Promise<string[]>;

  listApproved(overrides?: CallOverrides): Promise<string[]>;

  listDeclined(overrides?: CallOverrides): Promise<string[]>;

  listQued(overrides?: CallOverrides): Promise<string[]>;

  process(
    adr: string,
    approved: boolean,
    reason: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setControllers(
    operators: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRegistry(
    adr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    add(adr: string, uuid: BytesLike, overrides?: CallOverrides): Promise<void>;

    controllers(overrides?: CallOverrides): Promise<string[]>;

    getRegistry(overrides?: CallOverrides): Promise<string>;

    getStatus(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    info(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { status: BigNumber; uuid: string }>;

    isController(adr: string, overrides?: CallOverrides): Promise<boolean>;

    list(overrides?: CallOverrides): Promise<string[]>;

    listApproved(overrides?: CallOverrides): Promise<string[]>;

    listDeclined(overrides?: CallOverrides): Promise<string[]>;

    listQued(overrides?: CallOverrides): Promise<string[]>;

    process(
      adr: string,
      approved: boolean,
      reason: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setControllers(
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setRegistry(adr: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    qued(
      capTable?: string | null
    ): TypedEventFilter<[string], { capTable: string }>;

    statusUpdate(
      capTable?: string | null,
      status?: null,
      reason?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { capTable: string; status: BigNumber; reason: string }
    >;
  };

  estimateGas: {
    add(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controllers(overrides?: CallOverrides): Promise<BigNumber>;

    getRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getStatus(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    info(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isController(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    list(overrides?: CallOverrides): Promise<BigNumber>;

    listApproved(overrides?: CallOverrides): Promise<BigNumber>;

    listDeclined(overrides?: CallOverrides): Promise<BigNumber>;

    listQued(overrides?: CallOverrides): Promise<BigNumber>;

    process(
      adr: string,
      approved: boolean,
      reason: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRegistry(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    add(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controllers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStatus(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    info(adr: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isController(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    list(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    listApproved(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    listDeclined(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    listQued(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    process(
      adr: string,
      approved: boolean,
      reason: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRegistry(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
