/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CapTableRegistryInterface extends ethers.utils.Interface {
  functions: {
    "add(address,bytes32)": FunctionFragment;
    "controllers()": FunctionFragment;
    "info(address)": FunctionFragment;
    "isController(address)": FunctionFragment;
    "list()": FunctionFragment;
    "listActive()": FunctionFragment;
    "remove(address)": FunctionFragment;
    "setControllers(address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "add",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controllers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "info", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isController",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "list", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "listActive",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "remove", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setControllers",
    values: [string[]]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "controllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "list", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllers",
    data: BytesLike
  ): Result;

  events: {
    "capTableAdded(address)": EventFragment;
    "capTableRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "capTableAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "capTableRemoved"): EventFragment;
}

export class CapTableRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CapTableRegistryInterface;

  functions: {
    add(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controllers(overrides?: CallOverrides): Promise<[string[]]>;

    info(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { uuid: string; active: boolean }>;

    isController(adr: string, overrides?: CallOverrides): Promise<[boolean]>;

    list(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    listActive(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    remove(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  add(
    adr: string,
    uuid: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controllers(overrides?: CallOverrides): Promise<string[]>;

  info(
    adr: string,
    overrides?: CallOverrides
  ): Promise<[string, boolean] & { uuid: string; active: boolean }>;

  isController(adr: string, overrides?: CallOverrides): Promise<boolean>;

  list(overrides?: CallOverrides): Promise<string[]>;

  listActive(overrides?: CallOverrides): Promise<string[]>;

  remove(
    adr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setControllers(
    operators: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    add(adr: string, uuid: BytesLike, overrides?: CallOverrides): Promise<void>;

    controllers(overrides?: CallOverrides): Promise<string[]>;

    info(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { uuid: string; active: boolean }>;

    isController(adr: string, overrides?: CallOverrides): Promise<boolean>;

    list(overrides?: CallOverrides): Promise<string[]>;

    listActive(overrides?: CallOverrides): Promise<string[]>;

    remove(adr: string, overrides?: CallOverrides): Promise<void>;

    setControllers(
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    capTableAdded(
      capTableAddress?: string | null
    ): TypedEventFilter<[string], { capTableAddress: string }>;

    capTableRemoved(
      capTableRemoved?: string | null
    ): TypedEventFilter<[string], { capTableRemoved: string }>;
  };

  estimateGas: {
    add(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controllers(overrides?: CallOverrides): Promise<BigNumber>;

    info(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isController(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    list(overrides?: CallOverrides): Promise<BigNumber>;

    listActive(overrides?: CallOverrides): Promise<BigNumber>;

    remove(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    add(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controllers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    info(adr: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isController(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    list(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    listActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    remove(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
