/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CapTableRegistryInterface extends ethers.utils.Interface {
  functions: {
    "approve(address)": FunctionFragment;
    "controllers()": FunctionFragment;
    "decline(address,bytes32)": FunctionFragment;
    "getActiveCount()": FunctionFragment;
    "getAddress(bytes32)": FunctionFragment;
    "getLastQuedAddress(bytes32)": FunctionFragment;
    "getList()": FunctionFragment;
    "getQuedCount()": FunctionFragment;
    "getStatus(address)": FunctionFragment;
    "getUuid(address)": FunctionFragment;
    "info(address)": FunctionFragment;
    "isController(address)": FunctionFragment;
    "que(address,bytes32)": FunctionFragment;
    "remove(address)": FunctionFragment;
    "setControllers(address[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "approve", values: [string]): string;
  encodeFunctionData(
    functionFragment: "controllers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decline",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastQuedAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getList", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getQuedCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values: [string]): string;
  encodeFunctionData(functionFragment: "getUuid", values: [string]): string;
  encodeFunctionData(functionFragment: "info", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "que",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "remove", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setControllers",
    values: [string[]]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "controllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLastQuedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getQuedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUuid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "que", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllers",
    data: BytesLike
  ): Result;

  events: {
    "capTableApproved(address)": EventFragment;
    "capTableDeclined(address,bytes32)": EventFragment;
    "capTableQued(address,bytes32)": EventFragment;
    "capTableRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "capTableApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "capTableDeclined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "capTableQued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "capTableRemoved"): EventFragment;
}

export class CapTableRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CapTableRegistryInterface;

  functions: {
    approve(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controllers(overrides?: CallOverrides): Promise<[string[]]>;

    decline(
      adr: string,
      reason: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getActiveCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { activeCapTables: BigNumber }>;

    getAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { capTableAddress: string }>;

    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { capTableAddress: string }>;

    getList(
      overrides?: CallOverrides
    ): Promise<[string[]] & { capTableList: string[] }>;

    getQuedCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { quedCapTables: BigNumber }>;

    getStatus(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { status: BigNumber }>;

    getUuid(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[string] & { uuid: string }>;

    info(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { uuid: string; active: BigNumber }>;

    isController(adr: string, overrides?: CallOverrides): Promise<[boolean]>;

    que(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    remove(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  approve(
    adr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controllers(overrides?: CallOverrides): Promise<string[]>;

  decline(
    adr: string,
    reason: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getActiveCount(overrides?: CallOverrides): Promise<BigNumber>;

  getAddress(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

  getLastQuedAddress(
    uuid: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getList(overrides?: CallOverrides): Promise<string[]>;

  getQuedCount(overrides?: CallOverrides): Promise<BigNumber>;

  getStatus(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

  getUuid(adr: string, overrides?: CallOverrides): Promise<string>;

  info(
    adr: string,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { uuid: string; active: BigNumber }>;

  isController(adr: string, overrides?: CallOverrides): Promise<boolean>;

  que(
    adr: string,
    uuid: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  remove(
    adr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setControllers(
    operators: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approve(adr: string, overrides?: CallOverrides): Promise<void>;

    controllers(overrides?: CallOverrides): Promise<string[]>;

    decline(
      adr: string,
      reason: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getActiveCount(overrides?: CallOverrides): Promise<BigNumber>;

    getAddress(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getList(overrides?: CallOverrides): Promise<string[]>;

    getQuedCount(overrides?: CallOverrides): Promise<BigNumber>;

    getStatus(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getUuid(adr: string, overrides?: CallOverrides): Promise<string>;

    info(
      adr: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { uuid: string; active: BigNumber }>;

    isController(adr: string, overrides?: CallOverrides): Promise<boolean>;

    que(adr: string, uuid: BytesLike, overrides?: CallOverrides): Promise<void>;

    remove(adr: string, overrides?: CallOverrides): Promise<void>;

    setControllers(
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    capTableApproved(
      capTableAddress?: string | null
    ): TypedEventFilter<[string], { capTableAddress: string }>;

    capTableDeclined(
      capTableAddress?: string | null,
      reason?: null
    ): TypedEventFilter<
      [string, string],
      { capTableAddress: string; reason: string }
    >;

    capTableQued(
      capTableAddress?: string | null,
      uuid?: BytesLike | null
    ): TypedEventFilter<
      [string, string],
      { capTableAddress: string; uuid: string }
    >;

    capTableRemoved(
      capTableAddress?: string | null
    ): TypedEventFilter<[string], { capTableAddress: string }>;
  };

  estimateGas: {
    approve(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controllers(overrides?: CallOverrides): Promise<BigNumber>;

    decline(
      adr: string,
      reason: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getActiveCount(overrides?: CallOverrides): Promise<BigNumber>;

    getAddress(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getList(overrides?: CallOverrides): Promise<BigNumber>;

    getQuedCount(overrides?: CallOverrides): Promise<BigNumber>;

    getStatus(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getUuid(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    info(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isController(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    que(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    remove(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approve(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controllers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decline(
      adr: string,
      reason: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getActiveCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getQuedCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStatus(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUuid(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    info(adr: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isController(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    que(
      adr: string,
      uuid: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    remove(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
