/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CapTableFactoryInterface extends ethers.utils.Interface {
  functions: {
    "getLastQuedAddress(bytes32)": FunctionFragment;
    "getCapTableRegistryAddress()": FunctionFragment;
    "createCapTable(bytes32,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLastQuedAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapTableRegistryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCapTable",
    values: [BytesLike, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLastQuedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapTableRegistryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCapTable",
    data: BytesLike
  ): Result;

  events: {};
}

export class CapTableFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CapTableFactoryInterface;

  functions: {
    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { quedCapTableRegistryAddress: string }>;

    getCapTableRegistryAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { capTableRegistryAddress: string }>;

    createCapTable(
      uuid: BytesLike,
      name: string,
      symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getLastQuedAddress(
    uuid: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getCapTableRegistryAddress(overrides?: CallOverrides): Promise<string>;

  createCapTable(
    uuid: BytesLike,
    name: string,
    symbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getCapTableRegistryAddress(overrides?: CallOverrides): Promise<string>;

    createCapTable(
      uuid: BytesLike,
      name: string,
      symbol: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCapTableRegistryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    createCapTable(
      uuid: BytesLike,
      name: string,
      symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLastQuedAddress(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCapTableRegistryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createCapTable(
      uuid: BytesLike,
      name: string,
      symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
