/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DVPHoldableLockableInterface extends ethers.utils.Interface {
  functions: {
    "canImplementInterfaceForAddress(bytes32,address)": FunctionFragment;
    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canImplementInterfaceForAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeHolds",
    values: [
      string,
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "canImplementInterfaceForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeHolds",
    data: BytesLike
  ): Result;

  events: {
    "ExecuteHolds(address,bytes32,address,bytes32,bytes32,address,address)": EventFragment;
    "ExecutedHold(bytes32,bytes32)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "TransferByPartition(bytes32,address,address,address,uint256,bytes,bytes)": EventFragment;
    "CreateNote(address,bytes32,bytes)": EventFragment;
    "DestroyNote(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExecuteHolds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedHold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferByPartition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateNote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DestroyNote"): EventFragment;
}

export class DVPHoldableLockable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DVPHoldableLockableInterface;

  functions: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32,address,address)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      token1Recipient: string,
      token2Recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  canImplementInterfaceForAddress(
    interfaceHash: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32)"(
    token1: string,
    token1HoldId: BytesLike,
    tokenStandard1: BigNumberish,
    token2: string,
    token2HoldId: BytesLike,
    tokenStandard2: BigNumberish,
    preimage: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32,address,address)"(
    token1: string,
    token1HoldId: BytesLike,
    tokenStandard1: BigNumberish,
    token2: string,
    token2HoldId: BytesLike,
    tokenStandard2: BigNumberish,
    preimage: BytesLike,
    token1Recipient: string,
    token2Recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32,address,address)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      token1Recipient: string,
      token2Recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ExecuteHolds(
      token1?: string | null,
      token1HoldId?: null,
      token2?: string | null,
      token2HoldId?: null,
      preimage?: null,
      token1Recipient?: null,
      token2Recipient?: null
    ): TypedEventFilter<
      [string, string, string, string, string, string, string],
      {
        token1: string;
        token1HoldId: string;
        token2: string;
        token2HoldId: string;
        preimage: string;
        token1Recipient: string;
        token2Recipient: string;
      }
    >;

    ExecutedHold(
      holdId?: BytesLike | null,
      lockPreimage?: null
    ): TypedEventFilter<
      [string, string],
      { holdId: string; lockPreimage: string }
    >;

    Transfer(
      from?: string | null,
      to?: string | null,
      tokens?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; tokens: BigNumber }
    >;

    TransferByPartition(
      fromPartition?: BytesLike | null,
      operator?: null,
      from?: string | null,
      to?: string | null,
      value?: null,
      data?: null,
      operatorData?: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber, string, string],
      {
        fromPartition: string;
        operator: string;
        from: string;
        to: string;
        value: BigNumber;
        data: string;
        operatorData: string;
      }
    >;

    CreateNote(
      owner?: string | null,
      noteHash?: BytesLike | null,
      metadata?: null
    ): TypedEventFilter<
      [string, string, string],
      { owner: string; noteHash: string; metadata: string }
    >;

    DestroyNote(
      owner?: string | null,
      noteHash?: BytesLike | null
    ): TypedEventFilter<[string, string], { owner: string; noteHash: string }>;
  };

  estimateGas: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32,address,address)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      token1Recipient: string,
      token2Recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "executeHolds(address,bytes32,uint8,address,bytes32,uint8,bytes32,address,address)"(
      token1: string,
      token1HoldId: BytesLike,
      tokenStandard1: BigNumberish,
      token2: string,
      token2HoldId: BytesLike,
      tokenStandard2: BigNumberish,
      preimage: BytesLike,
      token1Recipient: string,
      token2Recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
