/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ERC1400TokensValidatorMockInterface extends ethers.utils.Interface {
  functions: {
    "renounceAllowlistAdmin(address)": FunctionFragment;
    "registerTokenSetup(address,uint8,bool,bool,bool,bool,address[])": FunctionFragment;
    "retrieveHoldData(address,bytes32)": FunctionFragment;
    "totalSupplyOnHold(address)": FunctionFragment;
    "balanceOnHold(address,address)": FunctionFragment;
    "holdFrom(address,bytes32,address,address,address,bytes32,uint256,uint256,bytes32,bytes)": FunctionFragment;
    "canImplementInterfaceForAddress(bytes32,address)": FunctionFragment;
    "usedCertificateNonce(address,address)": FunctionFragment;
    "preHoldFor(address,bytes32,address,address,bytes32,uint256,uint256,bytes32,bytes)": FunctionFragment;
    "addBlocklisted(address,address)": FunctionFragment;
    "paused(address)": FunctionFragment;
    "isPauser(address,address)": FunctionFragment;
    "renounceCertificateSigner(address)": FunctionFragment;
    "renouncePauser(address)": FunctionFragment;
    "addAllowlisted(address,address)": FunctionFragment;
    "isAllowlistAdmin(address,address)": FunctionFragment;
    "totalSupplyOnHoldByPartition(address,bytes32)": FunctionFragment;
    "tokensToValidate(bytes,bytes32,address,address,address,uint256,bytes,bytes)": FunctionFragment;
    "preHoldForWithExpirationDate(address,bytes32,address,address,bytes32,uint256,uint256,bytes32,bytes)": FunctionFragment;
    "executeHold(address,bytes32,uint256,bytes32)": FunctionFragment;
    "unpause(address)": FunctionFragment;
    "spendableBalanceOf(address,address)": FunctionFragment;
    "renounceMinter(address)": FunctionFragment;
    "usedCertificateSalt(address,bytes32)": FunctionFragment;
    "isAllowlisted(address,address)": FunctionFragment;
    "setGranularityByPartition(address,bytes32,uint256)": FunctionFragment;
    "removeAllowlisted(address,address)": FunctionFragment;
    "executeHoldAndKeepOpen(address,bytes32,uint256,bytes32)": FunctionFragment;
    "spendableBalanceOfByPartition(address,bytes32,address)": FunctionFragment;
    "hold(address,bytes32,address,address,bytes32,uint256,uint256,bytes32,bytes)": FunctionFragment;
    "pause(address)": FunctionFragment;
    "holdWithExpirationDate(address,bytes32,address,address,bytes32,uint256,uint256,bytes32,bytes)": FunctionFragment;
    "canValidate(address,bytes,bytes32,address,address,address,uint256,bytes,bytes)": FunctionFragment;
    "holdFromWithExpirationDate(address,bytes32,address,address,address,bytes32,uint256,uint256,bytes32,bytes)": FunctionFragment;
    "removeBlocklisted(address,address)": FunctionFragment;
    "isCertificateSigner(address,address)": FunctionFragment;
    "isBlocklistAdmin(address,address)": FunctionFragment;
    "isBlocklisted(address,address)": FunctionFragment;
    "granularityByPartition(address,bytes32)": FunctionFragment;
    "retrieveTokenSetup(address)": FunctionFragment;
    "renewHoldWithExpirationDate(address,bytes32,uint256,bytes)": FunctionFragment;
    "releaseHold(address,bytes32)": FunctionFragment;
    "addBlocklistAdmin(address,address)": FunctionFragment;
    "addCertificateSigner(address,address)": FunctionFragment;
    "renewHold(address,bytes32,uint256,bytes)": FunctionFragment;
    "removeAllowlistAdmin(address,address)": FunctionFragment;
    "renounceBlocklistAdmin(address)": FunctionFragment;
    "balanceOnHoldByPartition(address,bytes32,address)": FunctionFragment;
    "removeCertificateSigner(address,address)": FunctionFragment;
    "addPauser(address,address)": FunctionFragment;
    "removeBlocklistAdmin(address,address)": FunctionFragment;
    "removePauser(address,address)": FunctionFragment;
    "addAllowlistAdmin(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "renounceAllowlistAdmin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTokenSetup",
    values: [string, BigNumberish, boolean, boolean, boolean, boolean, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveHoldData",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyOnHold",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOnHold",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "holdFrom",
    values: [
      string,
      BytesLike,
      string,
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "canImplementInterfaceForAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "usedCertificateNonce",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "preHoldFor",
    values: [
      string,
      BytesLike,
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addBlocklisted",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "paused", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceCertificateSigner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renouncePauser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAllowlisted",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowlistAdmin",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyOnHoldByPartition",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensToValidate",
    values: [
      BytesLike,
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "preHoldForWithExpirationDate",
    values: [
      string,
      BytesLike,
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeHold",
    values: [string, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values: [string]): string;
  encodeFunctionData(
    functionFragment: "spendableBalanceOf",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceMinter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "usedCertificateSalt",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowlisted",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGranularityByPartition",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowlisted",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeHoldAndKeepOpen",
    values: [string, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "spendableBalanceOfByPartition",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hold",
    values: [
      string,
      BytesLike,
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "pause", values: [string]): string;
  encodeFunctionData(
    functionFragment: "holdWithExpirationDate",
    values: [
      string,
      BytesLike,
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "canValidate",
    values: [
      string,
      BytesLike,
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "holdFromWithExpirationDate",
    values: [
      string,
      BytesLike,
      string,
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBlocklisted",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isCertificateSigner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocklistAdmin",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocklisted",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "granularityByPartition",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveTokenSetup",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renewHoldWithExpirationDate",
    values: [string, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseHold",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addBlocklistAdmin",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addCertificateSigner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renewHold",
    values: [string, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowlistAdmin",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceBlocklistAdmin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOnHoldByPartition",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCertificateSigner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addPauser",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBlocklistAdmin",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removePauser",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAllowlistAdmin",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "renounceAllowlistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTokenSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveHoldData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyOnHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOnHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "holdFrom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canImplementInterfaceForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedCertificateNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "preHoldFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceCertificateSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renouncePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllowlistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyOnHoldByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensToValidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preHoldForWithExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spendableBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedCertificateSalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGranularityByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeHoldAndKeepOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendableBalanceOfByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "holdWithExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canValidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holdFromWithExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCertificateSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlocklistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "granularityByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveTokenSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renewHoldWithExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addBlocklistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCertificateSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renewHold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowlistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceBlocklistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOnHoldByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCertificateSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeBlocklistAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAllowlistAdmin",
    data: BytesLike
  ): Result;

  events: {
    "HoldCreated(address,bytes32,bytes32,address,address,address,uint256,uint256,bytes32)": EventFragment;
    "HoldReleased(address,bytes32,address,uint8)": EventFragment;
    "HoldRenewed(address,bytes32,address,uint256,uint256)": EventFragment;
    "HoldExecuted(address,bytes32,address,uint256,uint256,bytes32)": EventFragment;
    "HoldExecutedAndKeptOpen(address,bytes32,address,uint256,uint256,bytes32)": EventFragment;
    "BlocklistedAdded(address,address)": EventFragment;
    "BlocklistedRemoved(address,address)": EventFragment;
    "BlocklistAdminAdded(address,address)": EventFragment;
    "BlocklistAdminRemoved(address,address)": EventFragment;
    "AllowlistedAdded(address,address)": EventFragment;
    "AllowlistedRemoved(address,address)": EventFragment;
    "AllowlistAdminAdded(address,address)": EventFragment;
    "AllowlistAdminRemoved(address,address)": EventFragment;
    "CertificateSignerAdded(address,address)": EventFragment;
    "CertificateSignerRemoved(address,address)": EventFragment;
    "Paused(address,address)": EventFragment;
    "Unpaused(address,address)": EventFragment;
    "PauserAdded(address,address)": EventFragment;
    "PauserRemoved(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HoldCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HoldReleased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HoldRenewed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HoldExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HoldExecutedAndKeptOpen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistedAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistedRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistAdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistAdminRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowlistedAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowlistedRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowlistAdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowlistAdminRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CertificateSignerAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CertificateSignerRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauserAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauserRemoved"): EventFragment;
}

export class ERC1400TokensValidatorMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ERC1400TokensValidatorMockInterface;

  functions: {
    renounceAllowlistAdmin(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerTokenSetup(
      token: string,
      certificateActivated: BigNumberish,
      allowlistActivated: boolean,
      blocklistActivated: boolean,
      granularityByPartitionActivated: boolean,
      holdsActivated: boolean,
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    retrieveHoldData(
      token: string,
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        string,
        number
      ] & {
        partition: string;
        sender: string;
        recipient: string;
        notary: string;
        value: BigNumber;
        expiration: BigNumber;
        secretHash: string;
        secret: string;
        status: number;
      }
    >;

    totalSupplyOnHold(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOnHold(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    holdFrom(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    usedCertificateNonce(
      token: string,
      sender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    preHoldFor(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addBlocklisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(token: string, overrides?: CallOverrides): Promise<[boolean]>;

    isPauser(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    renounceCertificateSigner(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renouncePauser(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addAllowlisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isAllowlistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    totalSupplyOnHoldByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokensToValidate(
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    preHoldForWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeHold(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spendableBalanceOf(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceMinter(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    usedCertificateSalt(
      token: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isAllowlisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setGranularityByPartition(
      token: string,
      partition: BytesLike,
      granularity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeAllowlisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeHoldAndKeepOpen(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spendableBalanceOfByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hold(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pause(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    holdWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canValidate(
      token: string,
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    holdFromWithExpirationDate(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeBlocklisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isCertificateSigner(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBlocklistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBlocklisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    granularityByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    retrieveTokenSetup(
      token: string,
      overrides?: CallOverrides
    ): Promise<[number, boolean, boolean, boolean, boolean, string[]]>;

    renewHoldWithExpirationDate(
      token: string,
      holdId: BytesLike,
      expiration: BigNumberish,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    releaseHold(
      token: string,
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addBlocklistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addCertificateSigner(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renewHold(
      token: string,
      holdId: BytesLike,
      timeToExpiration: BigNumberish,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeAllowlistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceBlocklistAdmin(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balanceOnHoldByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    removeCertificateSigner(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addPauser(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeBlocklistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removePauser(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addAllowlistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  renounceAllowlistAdmin(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerTokenSetup(
    token: string,
    certificateActivated: BigNumberish,
    allowlistActivated: boolean,
    blocklistActivated: boolean,
    granularityByPartitionActivated: boolean,
    holdsActivated: boolean,
    operators: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  retrieveHoldData(
    token: string,
    holdId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      string,
      string,
      number
    ] & {
      partition: string;
      sender: string;
      recipient: string;
      notary: string;
      value: BigNumber;
      expiration: BigNumber;
      secretHash: string;
      secret: string;
      status: number;
    }
  >;

  totalSupplyOnHold(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOnHold(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  holdFrom(
    token: string,
    holdId: BytesLike,
    sender: string,
    recipient: string,
    notary: string,
    partition: BytesLike,
    value: BigNumberish,
    timeToExpiration: BigNumberish,
    secretHash: BytesLike,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canImplementInterfaceForAddress(
    interfaceHash: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  usedCertificateNonce(
    token: string,
    sender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  preHoldFor(
    token: string,
    holdId: BytesLike,
    recipient: string,
    notary: string,
    partition: BytesLike,
    value: BigNumberish,
    timeToExpiration: BigNumberish,
    secretHash: BytesLike,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addBlocklisted(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(token: string, overrides?: CallOverrides): Promise<boolean>;

  isPauser(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  renounceCertificateSigner(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renouncePauser(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addAllowlisted(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isAllowlistAdmin(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  totalSupplyOnHoldByPartition(
    token: string,
    partition: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokensToValidate(
    payload: BytesLike,
    partition: BytesLike,
    operator: string,
    from: string,
    to: string,
    value: BigNumberish,
    data: BytesLike,
    operatorData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  preHoldForWithExpirationDate(
    token: string,
    holdId: BytesLike,
    recipient: string,
    notary: string,
    partition: BytesLike,
    value: BigNumberish,
    expiration: BigNumberish,
    secretHash: BytesLike,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeHold(
    token: string,
    holdId: BytesLike,
    value: BigNumberish,
    secret: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spendableBalanceOf(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceMinter(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  usedCertificateSalt(
    token: string,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isAllowlisted(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setGranularityByPartition(
    token: string,
    partition: BytesLike,
    granularity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeAllowlisted(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeHoldAndKeepOpen(
    token: string,
    holdId: BytesLike,
    value: BigNumberish,
    secret: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spendableBalanceOfByPartition(
    token: string,
    partition: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hold(
    token: string,
    holdId: BytesLike,
    recipient: string,
    notary: string,
    partition: BytesLike,
    value: BigNumberish,
    timeToExpiration: BigNumberish,
    secretHash: BytesLike,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pause(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  holdWithExpirationDate(
    token: string,
    holdId: BytesLike,
    recipient: string,
    notary: string,
    partition: BytesLike,
    value: BigNumberish,
    expiration: BigNumberish,
    secretHash: BytesLike,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canValidate(
    token: string,
    payload: BytesLike,
    partition: BytesLike,
    operator: string,
    from: string,
    to: string,
    value: BigNumberish,
    data: BytesLike,
    operatorData: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  holdFromWithExpirationDate(
    token: string,
    holdId: BytesLike,
    sender: string,
    recipient: string,
    notary: string,
    partition: BytesLike,
    value: BigNumberish,
    expiration: BigNumberish,
    secretHash: BytesLike,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeBlocklisted(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isCertificateSigner(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isBlocklistAdmin(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isBlocklisted(
    token: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  granularityByPartition(
    token: string,
    partition: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  retrieveTokenSetup(
    token: string,
    overrides?: CallOverrides
  ): Promise<[number, boolean, boolean, boolean, boolean, string[]]>;

  renewHoldWithExpirationDate(
    token: string,
    holdId: BytesLike,
    expiration: BigNumberish,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  releaseHold(
    token: string,
    holdId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addBlocklistAdmin(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addCertificateSigner(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renewHold(
    token: string,
    holdId: BytesLike,
    timeToExpiration: BigNumberish,
    certificate: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeAllowlistAdmin(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceBlocklistAdmin(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balanceOnHoldByPartition(
    token: string,
    partition: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeCertificateSigner(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addPauser(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeBlocklistAdmin(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removePauser(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addAllowlistAdmin(
    token: string,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    renounceAllowlistAdmin(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerTokenSetup(
      token: string,
      certificateActivated: BigNumberish,
      allowlistActivated: boolean,
      blocklistActivated: boolean,
      granularityByPartitionActivated: boolean,
      holdsActivated: boolean,
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    retrieveHoldData(
      token: string,
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        string,
        number
      ] & {
        partition: string;
        sender: string;
        recipient: string;
        notary: string;
        value: BigNumber;
        expiration: BigNumber;
        secretHash: string;
        secret: string;
        status: number;
      }
    >;

    totalSupplyOnHold(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOnHold(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    holdFrom(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    usedCertificateNonce(
      token: string,
      sender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    preHoldFor(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addBlocklisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    paused(token: string, overrides?: CallOverrides): Promise<boolean>;

    isPauser(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceCertificateSigner(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renouncePauser(token: string, overrides?: CallOverrides): Promise<void>;

    addAllowlisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isAllowlistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    totalSupplyOnHoldByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokensToValidate(
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    preHoldForWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    executeHold(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unpause(token: string, overrides?: CallOverrides): Promise<void>;

    spendableBalanceOf(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceMinter(token: string, overrides?: CallOverrides): Promise<void>;

    usedCertificateSalt(
      token: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAllowlisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setGranularityByPartition(
      token: string,
      partition: BytesLike,
      granularity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    removeAllowlisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    executeHoldAndKeepOpen(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    spendableBalanceOfByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hold(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    pause(token: string, overrides?: CallOverrides): Promise<void>;

    holdWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    canValidate(
      token: string,
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    holdFromWithExpirationDate(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeBlocklisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isCertificateSigner(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBlocklistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBlocklisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    granularityByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retrieveTokenSetup(
      token: string,
      overrides?: CallOverrides
    ): Promise<[number, boolean, boolean, boolean, boolean, string[]]>;

    renewHoldWithExpirationDate(
      token: string,
      holdId: BytesLike,
      expiration: BigNumberish,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    releaseHold(
      token: string,
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addBlocklistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addCertificateSigner(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renewHold(
      token: string,
      holdId: BytesLike,
      timeToExpiration: BigNumberish,
      certificate: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeAllowlistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceBlocklistAdmin(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOnHoldByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCertificateSigner(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addPauser(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeBlocklistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removePauser(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addAllowlistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    HoldCreated(
      token?: string | null,
      holdId?: BytesLike | null,
      partition?: null,
      sender?: null,
      recipient?: null,
      notary?: string | null,
      value?: null,
      expiration?: null,
      secretHash?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string
      ],
      {
        token: string;
        holdId: string;
        partition: string;
        sender: string;
        recipient: string;
        notary: string;
        value: BigNumber;
        expiration: BigNumber;
        secretHash: string;
      }
    >;

    HoldReleased(
      token?: string | null,
      holdId?: null,
      notary?: string | null,
      status?: null
    ): TypedEventFilter<
      [string, string, string, number],
      { token: string; holdId: string; notary: string; status: number }
    >;

    HoldRenewed(
      token?: string | null,
      holdId?: null,
      notary?: string | null,
      oldExpiration?: null,
      newExpiration?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        token: string;
        holdId: string;
        notary: string;
        oldExpiration: BigNumber;
        newExpiration: BigNumber;
      }
    >;

    HoldExecuted(
      token?: string | null,
      holdId?: null,
      notary?: string | null,
      heldValue?: null,
      transferredValue?: null,
      secret?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        token: string;
        holdId: string;
        notary: string;
        heldValue: BigNumber;
        transferredValue: BigNumber;
        secret: string;
      }
    >;

    HoldExecutedAndKeptOpen(
      token?: string | null,
      holdId?: null,
      notary?: string | null,
      heldValue?: null,
      transferredValue?: null,
      secret?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        token: string;
        holdId: string;
        notary: string;
        heldValue: BigNumber;
        transferredValue: BigNumber;
        secret: string;
      }
    >;

    BlocklistedAdded(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    BlocklistedRemoved(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    BlocklistAdminAdded(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    BlocklistAdminRemoved(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    AllowlistedAdded(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    AllowlistedRemoved(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    AllowlistAdminAdded(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    AllowlistAdminRemoved(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    CertificateSignerAdded(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    CertificateSignerRemoved(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    Paused(
      token?: string | null,
      account?: null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    Unpaused(
      token?: string | null,
      account?: null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    PauserAdded(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;

    PauserRemoved(
      token?: string | null,
      account?: string | null
    ): TypedEventFilter<[string, string], { token: string; account: string }>;
  };

  estimateGas: {
    renounceAllowlistAdmin(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerTokenSetup(
      token: string,
      certificateActivated: BigNumberish,
      allowlistActivated: boolean,
      blocklistActivated: boolean,
      granularityByPartitionActivated: boolean,
      holdsActivated: boolean,
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    retrieveHoldData(
      token: string,
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupplyOnHold(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOnHold(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    holdFrom(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    usedCertificateNonce(
      token: string,
      sender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    preHoldFor(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addBlocklisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    isPauser(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceCertificateSigner(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renouncePauser(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addAllowlisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isAllowlistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupplyOnHoldByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokensToValidate(
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    preHoldForWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeHold(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spendableBalanceOf(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceMinter(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    usedCertificateSalt(
      token: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAllowlisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setGranularityByPartition(
      token: string,
      partition: BytesLike,
      granularity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeAllowlisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeHoldAndKeepOpen(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spendableBalanceOfByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hold(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pause(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    holdWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canValidate(
      token: string,
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    holdFromWithExpirationDate(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeBlocklisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isCertificateSigner(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBlocklistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBlocklisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    granularityByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retrieveTokenSetup(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renewHoldWithExpirationDate(
      token: string,
      holdId: BytesLike,
      expiration: BigNumberish,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    releaseHold(
      token: string,
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addBlocklistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addCertificateSigner(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renewHold(
      token: string,
      holdId: BytesLike,
      timeToExpiration: BigNumberish,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeAllowlistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceBlocklistAdmin(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balanceOnHoldByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCertificateSigner(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addPauser(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeBlocklistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removePauser(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addAllowlistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    renounceAllowlistAdmin(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerTokenSetup(
      token: string,
      certificateActivated: BigNumberish,
      allowlistActivated: boolean,
      blocklistActivated: boolean,
      granularityByPartitionActivated: boolean,
      holdsActivated: boolean,
      operators: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    retrieveHoldData(
      token: string,
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupplyOnHold(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOnHold(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    holdFrom(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    usedCertificateNonce(
      token: string,
      sender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    preHoldFor(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addBlocklisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPauser(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceCertificateSigner(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renouncePauser(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addAllowlisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isAllowlistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupplyOnHoldByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokensToValidate(
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    preHoldForWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeHold(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spendableBalanceOf(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceMinter(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    usedCertificateSalt(
      token: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAllowlisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setGranularityByPartition(
      token: string,
      partition: BytesLike,
      granularity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeAllowlisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeHoldAndKeepOpen(
      token: string,
      holdId: BytesLike,
      value: BigNumberish,
      secret: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spendableBalanceOfByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hold(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      timeToExpiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    holdWithExpirationDate(
      token: string,
      holdId: BytesLike,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canValidate(
      token: string,
      payload: BytesLike,
      partition: BytesLike,
      operator: string,
      from: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    holdFromWithExpirationDate(
      token: string,
      holdId: BytesLike,
      sender: string,
      recipient: string,
      notary: string,
      partition: BytesLike,
      value: BigNumberish,
      expiration: BigNumberish,
      secretHash: BytesLike,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeBlocklisted(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isCertificateSigner(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBlocklistAdmin(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBlocklisted(
      token: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    granularityByPartition(
      token: string,
      partition: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    retrieveTokenSetup(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renewHoldWithExpirationDate(
      token: string,
      holdId: BytesLike,
      expiration: BigNumberish,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    releaseHold(
      token: string,
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addBlocklistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addCertificateSigner(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renewHold(
      token: string,
      holdId: BytesLike,
      timeToExpiration: BigNumberish,
      certificate: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeAllowlistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceBlocklistAdmin(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balanceOnHoldByPartition(
      token: string,
      partition: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeCertificateSigner(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addPauser(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeBlocklistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removePauser(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addAllowlistAdmin(
      token: string,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
