/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AuthProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AuthProvider__factory>;
    getContractFactory(
      name: "CapTableFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CapTableFactory__factory>;
    getContractFactory(
      name: "CapTableRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CapTableRegistry__factory>;
    getContractFactory(
      name: "Controllable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Controllable__factory>;
    getContractFactory(
      name: "ControllerRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ControllerRole__factory>;
    getContractFactory(
      name: "ERC1400HoldableCertificateToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400HoldableCertificateToken__factory>;
    getContractFactory(
      name: "Extension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Extension__factory>;
    getContractFactory(
      name: "ERC1400",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400__factory>;
    getContractFactory(
      name: "IERC1820Registry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1820Registry__factory>;
    getContractFactory(
      name: "ERC1820ImplementerInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1820ImplementerInterface__factory>;
    getContractFactory(
      name: "ERC1820ImplementerInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1820ImplementerInterface__factory>;
    getContractFactory(
      name: "ERC1820Registry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1820Registry__factory>;
    getContractFactory(
      name: "ExampleClient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleClient__factory>;
    getContractFactory(
      name: "ExampleImplementer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleImplementer__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "ERC165MappingImplementation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165MappingImplementation__factory>;
    getContractFactory(
      name: "Homer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Homer__factory>;
    getContractFactory(
      name: "LegacyCBNoReturn",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyCBNoReturn__factory>;
    getContractFactory(
      name: "LegacyCBReturnFalse",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyCBReturnFalse__factory>;
    getContractFactory(
      name: "LegacyCBReturnTrue",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyCBReturnTrue__factory>;
    getContractFactory(
      name: "Lisa",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lisa__factory>;
    getContractFactory(
      name: "Simpson",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Simpson__factory>;
    getContractFactory(
      name: "SingletonFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SingletonFactory__factory>;
    getContractFactory(
      name: "ERC1400AuthValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400AuthValidator__factory>;
    getContractFactory(
      name: "IMinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMinterRole__factory>;
    getContractFactory(
      name: "ERC1400TokensChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400TokensChecker__factory>;
    getContractFactory(
      name: "IERC1400Extended",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400Extended__factory>;
    getContractFactory(
      name: "ERC1400TokensValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400TokensValidator__factory>;
    getContractFactory(
      name: "IMinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMinterRole__factory>;
    getContractFactory(
      name: "IERC1400TokensChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400TokensChecker__factory>;
    getContractFactory(
      name: "IERC1400TokensValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400TokensValidator__factory>;
    getContractFactory(
      name: "IERC1400TokensRecipient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400TokensRecipient__factory>;
    getContractFactory(
      name: "IERC1400TokensSender",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400TokensSender__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "IAuthProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuthProvider__factory>;
    getContractFactory(
      name: "IERC1400",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400__factory>;
    getContractFactory(
      name: "ERC1820Implementer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1820Implementer__factory>;
    getContractFactory(
      name: "AllowlistMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AllowlistMock__factory>;
    getContractFactory(
      name: "BlocklistMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlocklistMock__factory>;
    getContractFactory(
      name: "CertificateSignerMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CertificateSignerMock__factory>;
    getContractFactory(
      name: "ClockMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ClockMock__factory>;
    getContractFactory(
      name: "ERC1400TokensRecipientMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400TokensRecipientMock__factory>;
    getContractFactory(
      name: "ERC1400TokensSenderMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400TokensSenderMock__factory>;
    getContractFactory(
      name: "ERC1400TokensValidatorMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400TokensValidatorMock__factory>;
    getContractFactory(
      name: "IMinterMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMinterMock__factory>;
    getContractFactory(
      name: "ExtensionMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExtensionMock__factory>;
    getContractFactory(
      name: "FakeERC1400Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FakeERC1400Mock__factory>;
    getContractFactory(
      name: "MinterMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterMock__factory>;
    getContractFactory(
      name: "PauserMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PauserMock__factory>;
    getContractFactory(
      name: "AllowlistAdminRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AllowlistAdminRole__factory>;
    getContractFactory(
      name: "AllowlistedRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AllowlistedRole__factory>;
    getContractFactory(
      name: "BlocklistAdminRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlocklistAdminRole__factory>;
    getContractFactory(
      name: "BlocklistedRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlocklistedRole__factory>;
    getContractFactory(
      name: "CertificateSignerRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CertificateSignerRole__factory>;
    getContractFactory(
      name: "MinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterRole__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "PauserRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PauserRole__factory>;
    getContractFactory(
      name: "ERC1400HoldableToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1400HoldableToken__factory>;
    getContractFactory(
      name: "Extension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Extension__factory>;
    getContractFactory(
      name: "ERC20HoldableToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20HoldableToken__factory>;
    getContractFactory(
      name: "ERC20Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Token__factory>;
    getContractFactory(
      name: "ERC721Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Token__factory>;
    getContractFactory(
      name: "IERC20HoldableToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20HoldableToken__factory>;
    getContractFactory(
      name: "BatchBalanceReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BatchBalanceReader__factory>;
    getContractFactory(
      name: "IERC1400Extended",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1400Extended__factory>;
    getContractFactory(
      name: "BatchTokenIssuer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BatchTokenIssuer__factory>;
    getContractFactory(
      name: "IMinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMinterRole__factory>;
    getContractFactory(
      name: "DVP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DVP__factory>;
    getContractFactory(
      name: "DVPHoldableLockable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DVPHoldableLockable__factory>;
    getContractFactory(
      name: "HoldableERC1400TokenExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HoldableERC1400TokenExtension__factory>;
    getContractFactory(
      name: "FundIssuer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FundIssuer__factory>;
    getContractFactory(
      name: "MinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterRole__factory>;
    getContractFactory(
      name: "PauserRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PauserRole__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "ERC20Detailed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Detailed__factory>;
    getContractFactory(
      name: "ERC20Mintable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Mintable__factory>;
    getContractFactory(
      name: "ERC20Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Pausable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Burnable__factory>;
    getContractFactory(
      name: "ERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Enumerable__factory>;
    getContractFactory(
      name: "ERC721Full",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Full__factory>;
    getContractFactory(
      name: "ERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Metadata__factory>;
    getContractFactory(
      name: "ERC721Mintable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Mintable__factory>;
    getContractFactory(
      name: "ERC721Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Pausable__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
