/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IERC20HoldableTokenInterface extends ethers.utils.Interface {
  functions: {
    "executeHold(bytes32,bytes32)": FunctionFragment;
    "totalSupplyOnHold()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "releaseHold(bytes32)": FunctionFragment;
    "grossBalanceOf(address)": FunctionFragment;
    "hold(address,address,uint256,uint256,bytes32)": FunctionFragment;
    "holdStatus(bytes32)": FunctionFragment;
    "holdBalanceOf(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeHold",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyOnHold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "releaseHold",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grossBalanceOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hold",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "holdStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "holdBalanceOf",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyOnHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseHold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grossBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "holdStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "holdBalanceOf",
    data: BytesLike
  ): Result;

  events: {
    "NewHold(bytes32,address,address,uint256,uint256,bytes32)": EventFragment;
    "ExecutedHold(bytes32,bytes32,address)": EventFragment;
    "ReleaseHold(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewHold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedHold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReleaseHold"): EventFragment;
}

export class IERC20HoldableToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IERC20HoldableTokenInterface;

  functions: {
    "executeHold(bytes32,bytes32)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "executeHold(bytes32,bytes32,address)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "executeHold(bytes32)"(
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalSupplyOnHold(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    releaseHold(
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    grossBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hold(
      recipient: string,
      notary: string,
      amount: BigNumberish,
      expirationDateTime: BigNumberish,
      lockHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    holdStatus(holdId: BytesLike, overrides?: CallOverrides): Promise<[number]>;

    holdBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  "executeHold(bytes32,bytes32)"(
    holdId: BytesLike,
    lockPreimage: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "executeHold(bytes32,bytes32,address)"(
    holdId: BytesLike,
    lockPreimage: BytesLike,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "executeHold(bytes32)"(
    holdId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalSupplyOnHold(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  releaseHold(
    holdId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  grossBalanceOf(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hold(
    recipient: string,
    notary: string,
    amount: BigNumberish,
    expirationDateTime: BigNumberish,
    lockHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  holdStatus(holdId: BytesLike, overrides?: CallOverrides): Promise<number>;

  holdBalanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    "executeHold(bytes32,bytes32)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeHold(bytes32,bytes32,address)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeHold(bytes32)"(
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    totalSupplyOnHold(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    releaseHold(holdId: BytesLike, overrides?: CallOverrides): Promise<void>;

    grossBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hold(
      recipient: string,
      notary: string,
      amount: BigNumberish,
      expirationDateTime: BigNumberish,
      lockHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    holdStatus(holdId: BytesLike, overrides?: CallOverrides): Promise<number>;

    holdBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    NewHold(
      holdId?: BytesLike | null,
      recipient?: string | null,
      notary?: string | null,
      amount?: null,
      expirationDateTime?: null,
      lockHash?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        holdId: string;
        recipient: string;
        notary: string;
        amount: BigNumber;
        expirationDateTime: BigNumber;
        lockHash: string;
      }
    >;

    ExecutedHold(
      holdId?: BytesLike | null,
      lockPreimage?: null,
      recipient?: null
    ): TypedEventFilter<
      [string, string, string],
      { holdId: string; lockPreimage: string; recipient: string }
    >;

    ReleaseHold(
      holdId?: BytesLike | null,
      sender?: null
    ): TypedEventFilter<[string, string], { holdId: string; sender: string }>;
  };

  estimateGas: {
    "executeHold(bytes32,bytes32)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "executeHold(bytes32,bytes32,address)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "executeHold(bytes32)"(
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalSupplyOnHold(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    releaseHold(
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    grossBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hold(
      recipient: string,
      notary: string,
      amount: BigNumberish,
      expirationDateTime: BigNumberish,
      lockHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    holdStatus(
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    holdBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "executeHold(bytes32,bytes32)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "executeHold(bytes32,bytes32,address)"(
      holdId: BytesLike,
      lockPreimage: BytesLike,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "executeHold(bytes32)"(
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalSupplyOnHold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    releaseHold(
      holdId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    grossBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hold(
      recipient: string,
      notary: string,
      amount: BigNumberish,
      expirationDateTime: BigNumberish,
      lockHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    holdStatus(
      holdId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    holdBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
